### ISSUE TITLE
Sync to dropbox

### ISSUE THREAD

**Issue by wtuuju** [jffrymrtn/temaki#6]
I am not agree to use Dropbox as sync server. Mainly because I am very concerned about my private life, and letting my personal data to a third company worry me (and also a lot of people).

If a synchronization option is developped, please leave the choice to the user to sync with Dropbox or with its own server.

**Comment by ghost** [comment]
Hey,

No worries. I'm putting sync off on hold because of the current structure of the file system and the conflicts it has with using Dropbox's datastore. That means, unfortunately, I don't expect to have Temaki to have sync anytime.

But if, somehow, sync comes to Temaki, users will definitely have a choice as to whether or not to enable sync. Personally, I like to keep things private and local too :).

Thanks.
